server:
  port: 8166
  servlet:
    context-path: /web-new-booking-bookings
utils:
  booking:
    prefix: SPRING_WEB_APP_
integrations:
  core-service:
    url: http://localhost:5555/core
    connect-timeout: 2000
    read-timeout: 10000
    write-timeout: 2000